Jesus always saves
Wag kalimutan mag git add .
Saka mag git commit bawat pag tapos ng isang unit of work
(hilig mo mag isang bagsakang commit eh. *tsk tsk*)
wag kalimutan mag lagay ng message at description
Then sync changes
Then boom!

Pede ka na rin dumirekta sa source control if want mo mag git add.
at git commit sabay.

Gawa ka rin lagi README for summary!

----------------------------
DON'T FORGET TO PULL!
